/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PolybotUiModule extends AbstractPolybotUiModule {
}
