/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.validation;

import fr.unice.polytech.dziri.polybot.validation.AbstractPolybotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PolybotValidator extends AbstractPolybotValidator {
}
