/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPolybotScopeProvider extends DelegatingScopeProvider {
}
