/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PolybotStandaloneSetup extends PolybotStandaloneSetupGenerated {

	def static void doSetup() {
		new PolybotStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
