/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ui;

import fr.unice.polytech.dziri.polybot.ui.AbstractPolybotUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PolybotUiModule extends AbstractPolybotUiModule {
  public PolybotUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
