/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ui.contentassist;

import fr.unice.polytech.dziri.polybot.ui.contentassist.AbstractPolybotProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PolybotProposalProvider extends AbstractPolybotProposalProvider {
}
