/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.dziri.polybot.PolybotRuntimeModule;
import fr.unice.polytech.dziri.polybot.PolybotStandaloneSetup;
import fr.unice.polytech.dziri.polybot.ide.PolybotIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PolybotIdeSetup extends PolybotStandaloneSetup {
  @Override
  public Injector createInjector() {
    PolybotRuntimeModule _polybotRuntimeModule = new PolybotRuntimeModule();
    PolybotIdeModule _polybotIdeModule = new PolybotIdeModule();
    return Guice.createInjector(Modules2.mixin(_polybotRuntimeModule, _polybotIdeModule));
  }
}
