/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ide;

import fr.unice.polytech.dziri.polybot.ide.AbstractPolybotIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PolybotIdeModule extends AbstractPolybotIdeModule {
}
