/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.dziri.polybot.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PolybotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.unice.polytech.dziri.polybot.Polybot");
	}

}
