/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot;

import fr.unice.polytech.dziri.polybot.PolybotStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolybotStandaloneSetup extends PolybotStandaloneSetupGenerated {
  public static void doSetup() {
    new PolybotStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
