/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dziri.polybot;

import fr.unice.polytech.dziri.polybot.AbstractPolybotRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolybotRuntimeModule extends AbstractPolybotRuntimeModule {
}
